# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1ef32ddecd08f1461163ccafe76ca264dbfe0f257c88f0c96f579a898005d86eefbd5e2be5498af808113a4619104e3e246cda1d1e1552354b60841c395501

test:
  secret_key_base: 3b037a1bae4ec977f925c8eda3fbb4a593eb590bfdfbcd87acc84f53df24899fbed68c1a7a6ccc3d7dd82212ca91c1cc55bbae6166242e300f2680ecdc4a4b3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
